source 'http://rubygems.org'

gem 'rails', '3.1.1'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'paperclip'
gem 'json'
gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', :branch => 'rails3'
gem "forum_monster"
gem 'activemerchant'
gem 'money'
gem 'soap4r'
gem "acts-as-taggable-on"
gem "yaml_db"
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'jquery-rails'
  gem 'execjs'
  gem 'therubyracer'
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end
#Para la busqueda
gem 'sunspot_rails'
gem 'sunspot_solr'

gem 'nokogiri'

gem 'will_paginate'

gem 'jquery-rails'

group :development do
	gem 'sunspot_solr'
       end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

